log-file: /var/logs/museum.log

http:
    use-tls: false

s3:
    hot_storage:
       primary: b2-eu-cen
       secondary: b2-eu-cen

# stripe:
#     path:
#         success: ?status=success&session_id={CHECKOUT_SESSION_ID}
#         cancel: ?status=fail&reason=canceled
