<<<<<<<< HEAD:.github/workflows/personal-preview-deploy.yml
name: "Personal Preview Deploy"
========
name: "Deploy (locker web)"
>>>>>>>> 5d7057973ea143f4f59a2ba36ced8887cce3f636:.github/workflows/locker-web-deploy.yml

on:
    # Also allow manually running the workflow
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: web

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
<<<<<<<< HEAD:.github/workflows/personal-preview-deploy.yml
                  submodules: recursive
========
                  persist-credentials: false
>>>>>>>> 5d7057973ea143f4f59a2ba36ced8887cce3f636:.github/workflows/locker-web-deploy.yml

            - name: Setup node and enable yarn caching
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "yarn"
                  cache-dependency-path: "web/yarn.lock"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

<<<<<<<< HEAD:.github/workflows/personal-preview-deploy.yml
            - name: Build photos
              run: yarn build:photos

            - name: Publish photos
========
            - name: Audit dependencies
              run: |
                  yarn audit --level critical || exit_code=$?
                  if [[ $exit_code -ge 16 ]]; then
                      echo "::error::Yarn audit found critical issues"
                      exit 1
                  fi

            - name: Build locker
              run: yarn build:locker

            - name: Publish locker
>>>>>>>> 5d7057973ea143f4f59a2ba36ced8887cce3f636:.github/workflows/locker-web-deploy.yml
              uses: cloudflare/wrangler-action@v3
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
<<<<<<<< HEAD:.github/workflows/personal-preview-deploy.yml
                  command: pages deploy --project-name=kanz --commit-dirty=true --branch=preview web/apps/photos/out
========
                  command: pages deploy --project-name=ente --commit-dirty=true --branch=deploy/locker web/apps/locker/out
>>>>>>>> 5d7057973ea143f4f59a2ba36ced8887cce3f636:.github/workflows/locker-web-deploy.yml
