name: "Personal Server Deploy"

on:
    push:
        branches: 
            - 'deploy'
        # paths: 
        #     - 'server'
    # Also allow manually running the workflow
    workflow_dispatch:

jobs:
  deploy_server:
    name: Deploy server to fly.io
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: server

    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          ENTE_S3_B2-EU-CEN_KEY: ${{ secrets.ENTE_S3_PRIMARY_KEY }}
          ENTE_S3_B2-EU-CEN_SECRET: ${{ secrets.ENTE_S3_PRIMARY_SECRET }}
          ENTE_S3_WASABI-EU-CENTRAL-2-DERIVED_KEY: ${{ secrets.ENTE_S3_MLDATA_KEY }}
          ENTE_S3_WASABI-EU-CENTRAL-2-DERIVED_SECRET: ${{ secrets.ENTE_S3_MLDATA_SECRET }}